services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgres
    ports:
      - 5423:5432

  app:
    build: .
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_DATABASE_URL=${NEXT_PUBLIC_DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: >
      bash -c "yarn prisma:migrate
      && yarn prisma:seed
      && yarn dev"

volumes:
  postgres-data:
